#!/bin/bash

curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Chair", "price": 49.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Table", "price": 99.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Sofa", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bed", "price": 499.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bookshelf", "price": 129.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Dresser", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Nightstand", "price": 59.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Wardrobe", "price": 349.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Desk", "price": 149.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Coffee Table", "price": 79.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Armchair", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Recliner", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bar Stool", "price": 49.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Dining Table", "price": 399.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Dining Chair", "price": 79.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "TV Stand", "price": 149.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Entertainment Center", "price": 499.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Console Table", "price": 129.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Buffet Table", "price": 249.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Sideboard", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Pantry Cabinet", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Kitchen Island", "price": 349.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bar Cart", "price": 129.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Ottoman", "price": 89.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Futon", "price": 249.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Chaise Lounge", "price": 399.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Loveseat", "price": 499.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Sectional Sofa", "price": 899.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Rocking Chair", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bench", "price": 149.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Patio Chair", "price": 99.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Patio Table", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Patio Sofa", "price": 399.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Hammock", "price": 89.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Swing Chair", "price": 249.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Outdoor Bench", "price": 149.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Grill Cart", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Picnic Table", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Folding Chair", "price": 39.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Folding Table", "price": 79.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bean Bag Chair", "price": 59.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Office Chair", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Computer Desk", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Gaming Chair", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Lounge Chair", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Massage Chair", "price": 599.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Standing Desk", "price": 399.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Storage Cabinet", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Wardrobe Closet", "price": 499.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Shoe Rack", "price": 49.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Hall Tree", "price": 149.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Room Divider", "price": 129.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Vanity Set", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Jewelry Armoire", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Makeup Organizer", "price": 79.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Laundry Hamper", "price": 49.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Ironing Board", "price": 39.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Drying Rack", "price": 29.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "File Cabinet", "price": 99.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Printer Stand", "price": 49.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Book Cart", "price": 79.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Magazine Rack", "price": 29.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Coat Rack", "price": 39.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Umbrella Stand", "price": 29.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Hat Rack", "price": 29.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Mirror", "price": 99.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Wall Shelf", "price": 49.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Floating Shelf", "price": 59.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Corner Shelf", "price": 69.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Picture Ledge", "price": 29.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "CD Storage", "price": 39.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "DVD Storage", "price": 49.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Vinyl Record Storage", "price": 59.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Wine Rack", "price": 79.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Wine Cabinet", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Liquor Cabinet", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Mini Bar", "price": 399.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bakers Rack", "price": 149.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Kitchen Cart", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Pantry Organizer", "price": 79.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Dish Rack", "price": 39.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Spice Rack", "price": 29.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Knife Block", "price": 49.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Cutlery Tray", "price": 19.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bread Box", "price": 29.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Fruit Basket", "price": 19.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Serving Cart", "price": 99.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Tea Trolley", "price": 129.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Bar Table", "price": 199.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Breakfast Nook", "price": 299.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "Dining Bench", "price": 149.99}'
curl -X POST http://localhost:3000/api/products -H "Content-Type: application/json" -d '{"name": "China Cabinet", "price": 499.99}'
